<script setup lang="ts">
definePageMeta({ middleware: ["auth", "admin-client"] });
useSeoMeta({ title: "称号迁移 · 躲避堡垒 3" });
type Grant = { grantId: string; titleKey: string; label: string; category: string; scope: "global" | "map"; mapName?: string; holderName: string; playerAccountId?: string; playerName?: string; playerId?: string; status: "unclaimed" | "active" | "revoked"; revokeReason?: string };
type Player = { playerAccountId: string; playerName: string; playerId: string };
const api = useAdminApi(); const query = ref(""); const grants = ref<Grant[]>([]); const players = ref<Player[]>([]); const selectedPlayerId = ref(""); const message = ref(""); const loading = ref(false);
const load = async () => { loading.value = true; try { const [grantResponse, playerResponse] = await Promise.all([api<{ items: Grant[] }>(`/v1/title-grants?query=${encodeURIComponent(query.value)}`), api<{ items: Player[] }>("/v1/player-accounts?page=1&pageSize=50")]); grants.value = grantResponse.items; players.value = playerResponse.items; } finally { loading.value = false; } };
const grant = async (row: Grant) => { if (!selectedPlayerId.value) return; await api("/v1/title-grants", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: { contractVersion: "1", playerAccountId: selectedPlayerId.value, historicalTitleGrantId: row.grantId } }); message.value = "已关联"; await load(); };
const revoke = async (row: Grant) => { const reason = window.prompt("请输入撤销原因")?.trim(); if (!reason) return; await api(`/v1/title-grants/${row.grantId}/revoke`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: { contractVersion: "1", reason } }); message.value = "已撤销"; await load(); };
onMounted(load);
</script>
<template><main class="title-admin page-shell"><NuxtLink class="text-button" to="/admin">返回管理后台</NuxtLink><section><p class="eyebrow">历史快照</p><h1 class="page-title">称号迁移</h1><p class="body-copy">确认后关联到玩家帐号。</p></section><p v-if="message" role="status">{{ message }}</p><div class="filters surface-card"><input v-model="query" placeholder="搜索持有者或称号" aria-label="搜索历史称号" @change="load" /><select v-model="selectedPlayerId" aria-label="选择玩家"><option value="">选择玩家帐号</option><option v-for="player in players" :key="player.playerAccountId" :value="player.playerAccountId">{{ player.playerName }}#{{ player.playerId }}</option></select><button class="secondary-button" type="button" @click="load">搜索</button></div><div class="grant-list"><article v-for="row in grants" :key="row.grantId" class="grant-row surface-card"><div><p>{{ row.holderName }} · {{ row.category }}</p><h2>{{ row.label }}<span v-if="row.mapName"> · {{ row.mapName }}</span></h2><small>{{ row.status === "unclaimed" ? "未关联" : row.status === "active" ? `已关联至 ${row.playerName}#${row.playerId}` : "已撤销" }}</small></div><button v-if="row.status === 'unclaimed'" class="primary-button" :disabled="!selectedPlayerId" type="button" @click="grant(row)">关联</button><button v-else-if="row.status === 'active'" class="text-button danger" type="button" @click="revoke(row)">撤销</button></article><p v-if="!loading && !grants.length">暂无匹配记录。</p></div></main></template>
<style scoped>.title-admin { padding-block: 88px 72px; }.title-admin section { margin: 28px 0; }.filters { display: flex; gap: 8px; padding: 10px; }.filters input, .filters select { min-height: 44px; min-width: 0; flex: 1; padding: 0 12px; border: 1px solid var(--line); border-radius: 9px; color: var(--text); background: var(--surface-raised); }.grant-list { display: grid; gap: 10px; margin-top: 16px; }.grant-row { display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 18px; }.grant-row p, .grant-row small { margin: 0; color: var(--quiet); font-size: .78rem; }.grant-row h2 { margin: 8px 0; font-size: 1.2rem; }.danger { color: var(--danger); }.text-button:active, .primary-button:active { transform: scale(.97); }@media (max-width: 620px) { .filters, .grant-row { align-items: stretch; flex-direction: column; } }</style>
